# Generated by Django 4.2.17 on 2026-07-13 21:55

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Tag',
                'verbose_name_plural': 'Project Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Full Case Study & Documentation')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Project URL')),
                ('repository_url', models.URLField(blank=True, null=True, verbose_name='Repository URL')),
                ('live_demo_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/', verbose_name='Thumbnail')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured Project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='projects.projecttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'), models.Index(fields=['is_featured'], name='projects_pr_is_feat_bfabaf_idx'), models.Index(fields=['deleted_at'], name='projects_pr_deleted_4c0d8c_idx')],
            },
        ),
    ]
