# Generated by Django 4.2.17 on 2026-07-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at', 'is_read'], 'verbose_name': 'Contact Inquiry', 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Sender IP'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Read Status'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(verbose_name='Project Details / Message'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['-created_at'], name='core_contac_created_cb5667_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['is_read', '-created_at'], name='core_contac_is_read_09ebc2_idx'),
        ),
    ]
