# Generated by Django 4.2.17 on 2026-07-14 08:18

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactinquiry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Domain Name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Short Description')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or SVG icon class name', max_length=50)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Technical Domain',
                'verbose_name_plural': 'Technical Domains',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Company / Client Name')),
                ('role_title', models.CharField(max_length=150, verbose_name='Job Title / Role')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location or Remote')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date (leave blank if current)')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Currently Working Here')),
                ('description', markdownx.models.MarkdownxField(verbose_name='Role Description & Achievements (Markdown Supported)')),
                ('company_url', models.URLField(blank=True, null=True, verbose_name='Company Website')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-is_current', '-start_date'],
                'indexes': [models.Index(fields=['-is_current', '-start_date'], name='core_workex_is_curr_fa8618_idx'), models.Index(fields=['-start_date'], name='core_workex_start_d_c4f0a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('proficiency', models.PositiveSmallIntegerField(default=80, help_text='Percentage from 1 to 100', verbose_name='Proficiency %')),
                ('is_featured', models.BooleanField(db_index=True, default=True, help_text='Show on front page summaries')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.technicaldomain', verbose_name='Technical Domain')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['sort_order', '-proficiency', 'name'],
                'indexes': [models.Index(fields=['domain', 'sort_order'], name='core_skill_domain__9fdcdd_idx'), models.Index(fields=['is_featured', '-proficiency'], name='core_skill_is_feat_3312d8_idx')],
            },
        ),
    ]
