# Generated by Django 4.2.17 on 2026-07-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technicaldomain_workexperience_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('profile_url', models.URLField(verbose_name='Profile URL')),
                ('username_handle', models.CharField(max_length=100, verbose_name='Username / Handle')),
                ('avatar_or_logo', models.ImageField(blank=True, null=True, upload_to='media_platforms/', verbose_name='Custom Avatar/Logo')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or SVG class/identifier for the platform logo', max_length=100)),
                ('platform_type', models.CharField(choices=[('stat_driven', 'Live Stats Platform (GitHub, LeetCode, etc.)'), ('simple_link', 'Simple Profile Link (LinkedIn, X, etc.)')], db_index=True, default='simple_link', max_length=20)),
                ('api_identifier', models.CharField(blank=True, help_text="Identifier used by the background stats fetcher (e.g., 'github', 'leetcode')", max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Social Platform',
                'verbose_name_plural': 'Social Platforms',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'platform_type', 'sort_order'], name='core_social_is_acti_4207e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Metric Label')),
                ('value', models.CharField(max_length=50, verbose_name='Metric Value')),
                ('stat_color', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('purple', 'Purple'), ('gray', 'Gray')], default='gray', max_length=20, verbose_name='Accent Color for UI Badge/Progress')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.socialplatform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Platform Stat',
                'verbose_name_plural': 'Platform Stats',
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['platform', 'sort_order'], name='core_platfo_platfor_bc01d1_idx')],
            },
        ),
    ]
