# Generated by Django 4.2.17 on 2026-07-19 09:28
#
# Hand-edited to preserve existing skill↔domain relations across the
# ForeignKey -> ManyToManyField refactor, AND to safely backfill the new
# `Skill.slug` unique column from the existing `name` values.
#
#   1. Snapshot (skill_id, domain_id) pairs into core_skill_domain_backup.
#   2. Apply the auto-generated schema changes (drop FK, add M2M, add
#      `Skill.slug` WITHOUT a unique constraint so we can backfill first).
#   3. Populate slug from name (with `-N` collision suffix) for every row.
#   4. Add the unique constraint on slug.
#   5. Restore the M2M relations from the snapshot and drop the backup.

from django.db import migrations, models
from django.utils.text import slugify


def snapshot_skill_domains(apps, schema_editor):
    """Stash the existing skill↔domain pairs before the FK is dropped."""
    Skill = apps.get_model("core", "Skill")
    schema_editor.execute(
        """
        CREATE TABLE IF NOT EXISTS core_skill_domain_backup (
            skill_pk   INTEGER NOT NULL,
            domain_pk  INTEGER NOT NULL
        )
        """
    )
    schema_editor.execute("DELETE FROM core_skill_domain_backup")
    for skill in Skill.objects.exclude(domain__isnull=True):
        schema_editor.execute(
            "INSERT INTO core_skill_domain_backup (skill_pk, domain_pk) VALUES (%s, %s)",
            [skill.pk, skill.domain_id],
        )


def populate_skill_slugs(apps, schema_editor):
    """Backfill Skill.slug from Skill.name, ensuring uniqueness across rows.

    Runs after the slug column is added but before the unique constraint
    is created. Slugifies the existing name and appends -2, -3, ... on
    collision so no two skills share a slug.
    """
    Skill = apps.get_model("core", "Skill")
    seen: set[str] = set()
    for skill in Skill.objects.order_by("pk"):
        base: str = slugify(skill.name) or f"skill-{skill.pk}"
        candidate: str = base
        counter: int = 1
        while candidate in seen:
            counter += 1
            candidate = f"{base}-{counter}"
        seen.add(candidate)
        skill.slug = candidate
        skill.save(update_fields=["slug"])


def restore_skill_domains(apps, schema_editor):
    """Re-attach the saved pairs through the new M2M after the schema flip."""
    Skill = apps.get_model("core", "Skill")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT skill_pk, domain_pk FROM core_skill_domain_backup")
        rows = cursor.fetchall()
    for skill_pk, domain_pk in rows:
        try:
            skill = Skill.objects.get(pk=skill_pk)
        except Skill.DoesNotExist:
            continue
        skill.domains.add(domain_pk)
    schema_editor.execute("DROP TABLE IF EXISTS core_skill_domain_backup")


def noop(apps, schema_editor):
    """Reverse helpers do nothing — the backup table is dropped in forward."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skill_proficiency'),
    ]

    operations = [
        # 1) Snapshot the existing FK mapping before the column is dropped.
        migrations.RunPython(snapshot_skill_domains, noop),

        # 2) Schema changes (auto-generated). Slug field is added WITHOUT
        #    `unique=True` so step 3 can populate it without violating the
        #    constraint; the unique constraint is added in step 4.
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='technicaldomain',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Technical Domain', 'verbose_name_plural': 'Technical Domains'},
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='core_skill_domain__9fdcdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='core_skill_is_feat_3312d8_idx',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='technicaldomain',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            # NO `unique=True` here — we backfill in step 3 first.
            field=models.SlugField(blank=True, max_length=100, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='technicaldomain',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first', verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='technicaldomain',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select all skills that apply to this technical domain.', related_name='domains', to='core.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='technicaldomain',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Domain Name'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['-proficiency'], name='core_skill_profici_83b438_idx'),
        ),

        # 3) Backfill slug from name (with collision suffixes) so the column
        #    is fully populated before we ask the DB to enforce uniqueness.
        migrations.RunPython(populate_skill_slugs, noop),

        # 4) Now safe: enforce uniqueness on slug.
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug'),
        ),

        # 5) Restore the M2M relations and drop the backup table.
        migrations.RunPython(restore_skill_domains, noop),
    ]