# Generated by Django 4.2.17 on 2026-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_skill_options_alter_technicaldomain_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display name (e.g. 'GitHub Repositories').", max_length=80, verbose_name='Metric Label')),
                ('value', models.CharField(help_text="Numeric or short text value (e.g. '42', '1.2k', '99.9%').", max_length=40, verbose_name='Metric Value')),
                ('icon', models.CharField(choices=[('repo', 'Repositories'), ('commit', 'Commits / Contributions'), ('deploy', 'Production Deployments'), ('pipeline', 'Automated Pipelines'), ('contrib', 'Open-Source Contributions'), ('uptime', 'Uptime / Availability')], default='repo', help_text='Inline SVG icon selector.', max_length=30, verbose_name='Icon Key')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Show on About Page')),
            ],
            options={
                'verbose_name': 'Engineering Stat',
                'verbose_name_plural': 'Engineering Stats',
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='core_engine_is_acti_06c1d3_idx')],
            },
        ),
    ]
